const CONFIRMUSER_PREFIX = 'user-confirmation';
const EMAIL_TITLE_ACCOUNTCREATION = 'Confirmación de cuenta';
const EMAIL_TITLE_ACCOUNTCHANGEPASSWORD = 'Cambio de contraseña';
const CONFIRMUSER_CAPTION = 'Estamos encantados de que se haya unido a nosotros.';
const CHANGEPASSWORDUSER_CAPTION = 'Usted a solicitado que se actualice su contraseña de usuario.';

module.exports = {
  CONFIRMUSER_PREFIX: CONFIRMUSER_PREFIX,
  EMAIL_TITLE_ACCOUNTCREATION: EMAIL_TITLE_ACCOUNTCREATION,
  EMAIL_TITLE_ACCOUNTCHANGEPASSWORD: EMAIL_TITLE_ACCOUNTCHANGEPASSWORD,
  CONFIRMUSER_CAPTION: CONFIRMUSER_CAPTION,
  CHANGEPASSWORDUSER_CAPTION: CHANGEPASSWORDUSER_CAPTION
};
